name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      tmate:
        type: boolean
        description: 'SSH debug'
        required: false
        default: false

permissions:
  packages: write
  contents: write

env:
  CCACHE_DIR: "/dev/shm/ccache"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Env cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ./
            /dev/shm/ccache
          key: env-cache-${{ github.sha }}
          restore-keys: env-cache-

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup env
        run: |
          sudo ln -sf /usr/bin/bash /usr/bin/sh
          #mkdir -p /dev/shm/ccache
          #sudo apt install ccache
          #ccache -M 5G
          #ccache -z

      - name: Build
        run: ./makeMtk -t blade10 n k

      - name: Release
        run: gh release create "build-$(date +%Y-%m-%d-%H-%M-%S)" out/Download/flash/kernel_blade10.bin
        env:
          GH_TOKEN: ${{ github.token }}

#      - name: Ccache statistics
#        if: ${{ !cancelled() }}
#        run: ccache -sv

      - uses: mxschmitt/action-tmate@v3
        if: ${{ inputs.tmate }}

      - name: Clean Repository
        if: ${{ !cancelled() }}
        run: |
          git clean -ffdx
          git reset --hard HEAD
